version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9870:9870"
      - "9000:9000"
    networks:
      - hadoop_network
    volumes:
      - namenode_data:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - namenode
    networks:
      - hadoop_network
    volumes:
      - datanode_data:/hadoop/dfs/data

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - namenode
      - datanode
    volumes:
      - ./Studi:/home/jovyan/work
    environment:
      - PYSPARK_SUBMIT_ARGS=--master local[*] pyspark-shell
      - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
      - SPARK_CONF_DIR=/usr/local/spark/conf
      - SPARK_HOME=/usr/local/spark
    networks:
      - hadoop_network

networks:
  hadoop_network:
    driver: bridge

volumes:
  namenode_data:
  datanode_data:
